#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0.2 effective-5.10 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
#ifndef DCLOUDUTSEXTAPI_SWIFT_H
#define DCLOUDUTSEXTAPI_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import DCloudUniappRuntime;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="DCloudUTSExtAPI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSString;

SWIFT_CLASS_NAMED("AppBaseInfoDeviceUtil")
@interface UTSSDKModulesDCloudUniGetAppBaseInfoAppBaseInfoDeviceUtil : NSObject
+ (NSString * _Nonnull)getAppID SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getAppName SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getHostName SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getHostTheme SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getHostLanguage SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getHostVersion SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getHostPackageName SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getAppVersion SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getAppVersionCode SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getAppWgtVersion SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getOsLanguage SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getOsLanguageNormal SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getAppInnerVersion SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getBundleId SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getSignature SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSJSONObject;

SWIFT_CLASS_NAMED("AppThemeChangeResult")
@interface UTSSDKModulesDCloudUniThemeAppThemeChangeResult : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified appTheme;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


@class UTSSDKModulesDCloudUniStorageClearStorageSuccess;
@class UniError;

SWIFT_CLASS_NAMED("ClearStorageOptions")
@interface UTSSDKModulesDCloudUniStorageClearStorageOptions : NSObject
@property (nonatomic, copy) void (^ _Nullable success)(UTSSDKModulesDCloudUniStorageClearStorageSuccess * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable fail)(UniError * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable complete)(id _Nonnull);
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSCallback;

SWIFT_CLASS_NAMED("ClearStorageOptionsJSONObject")
@interface UTSSDKModulesDCloudUniStorageClearStorageOptionsJSONObject : NSObject
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ClearStorageSuccess")
@interface UTSSDKModulesDCloudUniStorageClearStorageSuccess : NSObject
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("CrashManager")
@interface UTSSDKModulesDCloudUniCrashCrashManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIApplication;

SWIFT_CLASS_NAMED("CrashManagerHookProxy")
@interface UTSSDKModulesDCloudUniCrashCrashManagerHookProxy : NSObject <UTSiOSHookProxy>
- (BOOL)applicationDidFinishLaunchingWithOptions:(UIApplication * _Nullable)application :(NSDictionary<UIApplicationLaunchOptionsKey, id> * _Nullable)launchOptions SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("CrashManagerHookProxyByJs")
@interface UTSSDKModulesDCloudUniCrashCrashManagerHookProxyByJs : UTSSDKModulesDCloudUniCrashCrashManagerHookProxy
- (BOOL)applicationDidFinishLaunchingWithOptionsByJs:(UIApplication * _Nullable)application :(NSDictionary<UIApplicationLaunchOptionsKey, id> * _Nullable)launchOptions SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNumber;

SWIFT_CLASS_NAMED("CutoutRect")
@interface UTSSDKModulesDCloudUniGetSystemInfoCutoutRect : NSObject
@property (nonatomic, strong) NSNumber * _Null_unspecified left;
@property (nonatomic, strong) NSNumber * _Null_unspecified right;
@property (nonatomic, strong) NSNumber * _Null_unspecified top;
@property (nonatomic, strong) NSNumber * _Null_unspecified bottom;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end

@class NSCoder;
@protocol UIViewControllerTransitionCoordinator;
@class NSBundle;

SWIFT_CLASS("_TtC15DCloudUTSExtAPI23DCActionSheetController")
@interface DCActionSheetController : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)loadView;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator> _Nonnull)coordinator;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@class UITableView;
@class NSIndexPath;
@class UITableViewCell;
@class UIView;

@interface DCActionSheetController (SWIFT_EXTENSION(DCloudUTSExtAPI)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC15DCloudUTSExtAPI13DCAlertAction")
@interface DCAlertAction : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15DCloudUTSExtAPI19DCAlertActionButton")
@interface DCAlertActionButton : UIButton
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


/// /////////////////////////// DCAlertViewController /////////////////////
SWIFT_CLASS("_TtC15DCloudUTSExtAPI21DCAlertViewController")
@interface DCAlertViewController : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)loadView;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@protocol UIViewControllerAnimatedTransitioning;

@interface DCAlertViewController (SWIFT_EXTENSION(DCloudUTSExtAPI)) <UIViewControllerTransitioningDelegate>
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForPresentedController:(UIViewController * _Nonnull)presented presentingController:(UIViewController * _Nonnull)presenting sourceController:(UIViewController * _Nonnull)source SWIFT_WARN_UNUSED_RESULT;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForDismissedController:(UIViewController * _Nonnull)dismissed SWIFT_WARN_UNUSED_RESULT;
@end



SWIFT_CLASS("_TtC15DCloudUTSExtAPI14DCRIButtonItem")
@interface DCRIButtonItem : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("DeviceUtil")
@interface UTSSDKModulesDCloudUniGetDeviceInfoDeviceUtil : NSObject
+ (BOOL)isPad SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getOSVersion SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getLan SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getOrientation SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)hasRootPrivilege SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSSDKModulesDCloudUniExitExitSuccess;

SWIFT_CLASS_NAMED("ExitOptions")
@interface UTSSDKModulesDCloudUniExitExitOptions : NSObject
@property (nonatomic, copy) void (^ _Nullable success)(UTSSDKModulesDCloudUniExitExitSuccess * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable complete)(id _Nonnull);
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ExitOptionsJSONObject")
@interface UTSSDKModulesDCloudUniExitExitOptionsJSONObject : NSObject
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ExitSuccess")
@interface UTSSDKModulesDCloudUniExitExitSuccess : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified errMsg;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("GetAppAuthorizeSettingResult")
@interface UTSSDKModulesDCloudUniGetAppAuthorizeSettingGetAppAuthorizeSettingResult : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified albumAuthorized;
@property (nonatomic, copy) NSString * _Null_unspecified bluetoothAuthorized;
@property (nonatomic, copy) NSString * _Null_unspecified cameraAuthorized;
@property (nonatomic, copy) NSString * _Null_unspecified locationAuthorized;
@property (nonatomic, copy) NSString * _Nullable locationAccuracy;
@property (nonatomic) BOOL locationReducedAccuracy;
@property (nonatomic, copy) NSString * _Null_unspecified microphoneAuthorized;
@property (nonatomic, copy) NSString * _Null_unspecified notificationAuthorized;
@property (nonatomic, copy) NSString * _Nullable notificationAlertAuthorized;
@property (nonatomic, copy) NSString * _Nullable notificationBadgeAuthorized;
@property (nonatomic, copy) NSString * _Nullable notificationSoundAuthorized;
@property (nonatomic, copy) NSString * _Nullable phoneCalendarAuthorized;
@property (nonatomic, copy) NSString * _Nullable readPhoneCalendarAuthorized;
@property (nonatomic, copy) NSString * _Nullable writePhoneCalendarAuthorized;
@property (nonatomic, copy) NSString * _Nullable pasteboardAuthorized;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("GetAppBaseInfoOptions")
@interface UTSSDKModulesDCloudUniGetAppBaseInfoGetAppBaseInfoOptions : NSObject
@property (nonatomic, copy) NSArray<NSString *> * _Null_unspecified filter;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("GetAppBaseInfoOptionsJSONObject")
@interface UTSSDKModulesDCloudUniGetAppBaseInfoGetAppBaseInfoOptionsJSONObject : NSObject
@property (nonatomic, copy) NSArray<NSString *> * _Null_unspecified filter;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("GetAppBaseInfoResult")
@interface UTSSDKModulesDCloudUniGetAppBaseInfoGetAppBaseInfoResult : NSObject
@property (nonatomic, copy) NSString * _Nullable appId;
@property (nonatomic, copy) NSString * _Nullable appName;
@property (nonatomic, copy) NSString * _Nullable appVersion;
@property (nonatomic, copy) NSString * _Nullable appVersionCode;
@property (nonatomic, copy) NSString * _Nullable appLanguage;
@property (nonatomic, copy) NSString * _Nullable language;
@property (nonatomic, copy) NSString * _Nullable version;
@property (nonatomic, copy) NSString * _Nullable appWgtVersion;
@property (nonatomic, copy) NSString * _Nullable hostLanguage;
@property (nonatomic, copy) NSString * _Nullable hostVersion;
@property (nonatomic, copy) NSString * _Nullable hostName;
@property (nonatomic, copy) NSString * _Nullable hostPackageName;
@property (nonatomic, copy) NSString * _Nullable hostSDKVersion;
@property (nonatomic, copy) NSString * _Nullable hostTheme;
@property (nonatomic) BOOL isUniAppX;
@property (nonatomic, copy) NSString * _Nullable uniCompileVersion;
@property (nonatomic, copy) NSString * _Nullable uniCompilerVersion;
@property (nonatomic, copy) NSString * _Nullable uniPlatform;
@property (nonatomic, copy) NSString * _Nullable uniRuntimeVersion;
@property (nonatomic, strong) NSNumber * _Nullable uniCompileVersionCode;
@property (nonatomic, strong) NSNumber * _Nullable uniCompilerVersionCode;
@property (nonatomic, strong) NSNumber * _Nullable uniRuntimeVersionCode;
@property (nonatomic, copy) NSString * _Nullable packageName;
@property (nonatomic, copy) NSString * _Nullable bundleName;
@property (nonatomic, copy) NSString * _Nullable bundleId;
@property (nonatomic, copy) NSString * _Nullable signature;
@property (nonatomic, copy) NSString * _Nullable appTheme;
@property (nonatomic, copy) NSString * _Nullable channel;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("GetDeviceInfoOptions")
@interface UTSSDKModulesDCloudUniGetDeviceInfoGetDeviceInfoOptions : NSObject
@property (nonatomic, copy) NSArray<NSString *> * _Null_unspecified filter;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("GetDeviceInfoOptionsJSONObject")
@interface UTSSDKModulesDCloudUniGetDeviceInfoGetDeviceInfoOptionsJSONObject : NSObject
@property (nonatomic, copy) NSArray<NSString *> * _Null_unspecified filter;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("GetDeviceInfoResult")
@interface UTSSDKModulesDCloudUniGetDeviceInfoGetDeviceInfoResult : NSObject
@property (nonatomic, copy) NSString * _Nullable brand;
@property (nonatomic, copy) NSString * _Nullable deviceBrand;
@property (nonatomic, copy) NSString * _Nullable deviceId;
@property (nonatomic, copy) NSString * _Nullable model;
@property (nonatomic, copy) NSString * _Nullable deviceModel;
@property (nonatomic, copy) NSString * _Nullable deviceType;
@property (nonatomic, copy) NSString * _Nullable deviceOrientation;
@property (nonatomic, strong) NSNumber * _Nullable devicePixelRatio;
@property (nonatomic, copy) NSString * _Nullable system;
@property (nonatomic, copy) NSString * _Nullable platform;
@property (nonatomic) BOOL isRoot;
@property (nonatomic) BOOL isSimulator;
@property (nonatomic) BOOL isUSBDebugging;
@property (nonatomic, copy) NSString * _Nullable osName;
@property (nonatomic, copy) NSString * _Nullable osVersion;
@property (nonatomic, copy) NSString * _Nullable osLanguage;
@property (nonatomic, copy) NSString * _Nullable osTheme;
@property (nonatomic, strong) NSNumber * _Nullable osAndroidAPILevel;
@property (nonatomic, strong) NSNumber * _Nullable osHarmonySDKAPIVersion;
@property (nonatomic, copy) NSString * _Nullable osHarmonyDisplayVersion;
@property (nonatomic, copy) NSString * _Nullable romName;
@property (nonatomic, copy) NSString * _Nullable romVersion;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSSDKModulesDCloudUniPrivacyGetPrivacySettingSuccessResult;

SWIFT_CLASS_NAMED("GetPrivacySettingOptions")
@interface UTSSDKModulesDCloudUniPrivacyGetPrivacySettingOptions : NSObject
@property (nonatomic, copy) void (^ _Nullable success)(UTSSDKModulesDCloudUniPrivacyGetPrivacySettingSuccessResult * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable fail)(id _Nonnull);
@property (nonatomic, copy) void (^ _Nullable complete)(id _Nonnull);
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("GetPrivacySettingOptionsJSONObject")
@interface UTSSDKModulesDCloudUniPrivacyGetPrivacySettingOptionsJSONObject : NSObject
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("GetPrivacySettingSuccessResult")
@interface UTSSDKModulesDCloudUniPrivacyGetPrivacySettingSuccessResult : NSObject
@property (nonatomic) BOOL needAuthorization;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSSDKModulesDCloudUniStorageGetStorageInfoSuccess;

SWIFT_CLASS_NAMED("GetStorageInfoOptions")
@interface UTSSDKModulesDCloudUniStorageGetStorageInfoOptions : NSObject
@property (nonatomic, copy) void (^ _Nullable success)(UTSSDKModulesDCloudUniStorageGetStorageInfoSuccess * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable fail)(UniError * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable complete)(id _Nonnull);
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("GetStorageInfoOptionsJSONObject")
@interface UTSSDKModulesDCloudUniStorageGetStorageInfoOptionsJSONObject : NSObject
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("GetStorageInfoSuccess")
@interface UTSSDKModulesDCloudUniStorageGetStorageInfoSuccess : NSObject
@property (nonatomic, copy) NSArray<NSString *> * _Null_unspecified keys;
@property (nonatomic, strong) NSNumber * _Null_unspecified currentSize;
@property (nonatomic, strong) NSNumber * _Null_unspecified limitSize;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSSDKModulesDCloudUniStorageGetStorageSuccess;

SWIFT_CLASS_NAMED("GetStorageOptions")
@interface UTSSDKModulesDCloudUniStorageGetStorageOptions : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified key;
@property (nonatomic, copy) void (^ _Nullable success)(UTSSDKModulesDCloudUniStorageGetStorageSuccess * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable fail)(UniError * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable complete)(id _Nonnull);
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("GetStorageOptionsJSONObject")
@interface UTSSDKModulesDCloudUniStorageGetStorageOptionsJSONObject : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified key;
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("GetStorageSuccess")
@interface UTSSDKModulesDCloudUniStorageGetStorageSuccess : NSObject
@property (nonatomic) id _Nullable data;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSSDKModulesDCloudUniGetSystemInfoGetSystemInfoResult;

SWIFT_CLASS_NAMED("GetSystemInfoOptions")
@interface UTSSDKModulesDCloudUniGetSystemInfoGetSystemInfoOptions : NSObject
@property (nonatomic, copy) void (^ _Nullable success)(UTSSDKModulesDCloudUniGetSystemInfoGetSystemInfoResult * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable fail)(UniError * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable complete)(id _Nonnull);
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("GetSystemInfoOptionsJSONObject")
@interface UTSSDKModulesDCloudUniGetSystemInfoGetSystemInfoOptionsJSONObject : NSObject
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSSDKModulesDCloudUniGetSystemInfoSafeArea;
@class UTSSDKModulesDCloudUniGetSystemInfoSafeAreaInsets;

SWIFT_CLASS_NAMED("GetSystemInfoResult")
@interface UTSSDKModulesDCloudUniGetSystemInfoGetSystemInfoResult : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified SDKVersion;
@property (nonatomic, copy) NSString * _Null_unspecified appId;
@property (nonatomic, copy) NSString * _Null_unspecified appLanguage;
@property (nonatomic, copy) NSString * _Null_unspecified appName;
@property (nonatomic, copy) NSString * _Null_unspecified appVersion;
@property (nonatomic, copy) NSString * _Null_unspecified appVersionCode;
@property (nonatomic, copy) NSString * _Nullable appWgtVersion;
@property (nonatomic, copy) NSString * _Null_unspecified brand;
@property (nonatomic, copy) NSString * _Null_unspecified browserName;
@property (nonatomic, copy) NSString * _Null_unspecified browserVersion;
@property (nonatomic, copy) NSString * _Null_unspecified deviceId;
@property (nonatomic, copy) NSString * _Null_unspecified deviceBrand;
@property (nonatomic, copy) NSString * _Null_unspecified deviceModel;
@property (nonatomic, copy) NSString * _Null_unspecified deviceType;
@property (nonatomic, strong) NSNumber * _Null_unspecified devicePixelRatio;
@property (nonatomic, copy) NSString * _Null_unspecified deviceOrientation;
@property (nonatomic, copy) NSString * _Null_unspecified language;
@property (nonatomic, copy) NSString * _Nullable model;
@property (nonatomic, copy) NSString * _Null_unspecified osName;
@property (nonatomic, copy) NSString * _Null_unspecified osVersion;
@property (nonatomic, copy) NSString * _Null_unspecified osLanguage;
@property (nonatomic, copy) NSString * _Nullable osTheme;
@property (nonatomic, strong) NSNumber * _Null_unspecified pixelRatio;
@property (nonatomic, copy) NSString * _Null_unspecified platform;
@property (nonatomic, strong) NSNumber * _Null_unspecified screenWidth;
@property (nonatomic, strong) NSNumber * _Null_unspecified screenHeight;
@property (nonatomic, strong) NSNumber * _Null_unspecified statusBarHeight;
@property (nonatomic, copy) NSString * _Null_unspecified system;
@property (nonatomic, strong) UTSSDKModulesDCloudUniGetSystemInfoSafeArea * _Null_unspecified safeArea;
@property (nonatomic, strong) UTSSDKModulesDCloudUniGetSystemInfoSafeAreaInsets * _Null_unspecified safeAreaInsets;
@property (nonatomic, copy) NSString * _Null_unspecified ua;
@property (nonatomic, copy) NSString * _Null_unspecified uniCompileVersion;
@property (nonatomic, copy) NSString * _Null_unspecified uniCompilerVersion;
@property (nonatomic, copy) NSString * _Null_unspecified uniPlatform;
@property (nonatomic, copy) NSString * _Null_unspecified uniRuntimeVersion;
@property (nonatomic, strong) NSNumber * _Null_unspecified uniCompileVersionCode;
@property (nonatomic, strong) NSNumber * _Null_unspecified uniCompilerVersionCode;
@property (nonatomic, strong) NSNumber * _Null_unspecified uniRuntimeVersionCode;
@property (nonatomic, copy) NSString * _Null_unspecified version;
@property (nonatomic, copy) NSString * _Null_unspecified romName;
@property (nonatomic, copy) NSString * _Null_unspecified romVersion;
@property (nonatomic, strong) NSNumber * _Null_unspecified windowWidth;
@property (nonatomic, strong) NSNumber * _Null_unspecified windowHeight;
@property (nonatomic, strong) NSNumber * _Null_unspecified windowTop;
@property (nonatomic, strong) NSNumber * _Null_unspecified windowBottom;
@property (nonatomic, strong) NSNumber * _Nullable osAndroidAPILevel;
@property (nonatomic, strong) NSNumber * _Nullable osHarmonySDKAPIVersion;
@property (nonatomic, copy) NSString * _Nullable osHarmonyDisplayVersion;
@property (nonatomic, copy) NSString * _Nullable appTheme;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("GetSystemSettingResult")
@interface UTSSDKModulesDCloudUniGetSystemSettingGetSystemSettingResult : NSObject
@property (nonatomic) BOOL bluetoothEnabled;
@property (nonatomic, copy) NSString * _Nullable bluetoothError;
@property (nonatomic) BOOL locationEnabled;
@property (nonatomic) BOOL wifiEnabled;
@property (nonatomic, copy) NSString * _Nullable wifiError;
@property (nonatomic, copy) NSString * _Null_unspecified deviceOrientation;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("GetWindowInfoResult")
@interface UTSSDKModulesDCloudUniGetSystemInfoGetWindowInfoResult : NSObject
@property (nonatomic, strong) NSNumber * _Null_unspecified pixelRatio;
@property (nonatomic, strong) NSNumber * _Null_unspecified screenWidth;
@property (nonatomic, strong) NSNumber * _Null_unspecified screenHeight;
@property (nonatomic, strong) NSNumber * _Null_unspecified windowWidth;
@property (nonatomic, strong) NSNumber * _Null_unspecified windowHeight;
@property (nonatomic, strong) NSNumber * _Null_unspecified statusBarHeight;
@property (nonatomic, strong) NSNumber * _Null_unspecified windowTop;
@property (nonatomic, strong) NSNumber * _Null_unspecified windowBottom;
@property (nonatomic, strong) UTSSDKModulesDCloudUniGetSystemInfoSafeArea * _Null_unspecified safeArea;
@property (nonatomic, strong) UTSSDKModulesDCloudUniGetSystemInfoSafeAreaInsets * _Null_unspecified safeAreaInsets;
@property (nonatomic, strong) NSNumber * _Null_unspecified screenTop;
@property (nonatomic, copy) NSArray<UTSSDKModulesDCloudUniGetSystemInfoCutoutRect *> * _Nullable cutoutArea;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("HTMLParserAttr")
@interface UTSSDKModulesDCloudUniRichTextHTMLParserAttr : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull value;
- (nonnull instancetype)init:(NSString * _Nonnull)name :(NSString * _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("HTMLParserHandler")
@interface UTSSDKModulesDCloudUniRichTextHTMLParserHandler : NSObject
@property (nonatomic, copy) void (^ _Nullable start)(NSString * _Nonnull, NSArray<UTSSDKModulesDCloudUniRichTextHTMLParserAttr *> * _Nonnull, BOOL);
@property (nonatomic, copy) void (^ _Nullable end)(NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable chars)(NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable comment)(NSString * _Nonnull);
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol UniPage;
@class UTSSDKModulesDCloudUniModalUniHideModalResult;

SWIFT_CLASS_NAMED("HideModalOptions")
@interface UTSSDKModulesDCloudUniModalHideModalOptions : NSObject
@property (nonatomic, strong) id <UniPage> _Nullable modalPage;
@property (nonatomic, copy) void (^ _Nullable success)(UTSSDKModulesDCloudUniModalUniHideModalResult * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable complete)(id _Nonnull);
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("HideModalOptionsJSONObject")
@interface UTSSDKModulesDCloudUniModalHideModalOptionsJSONObject : NSObject
@property (nonatomic, strong) id <UniPage> _Nullable modalPage;
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15DCloudUTSExtAPI7MCToast")
@interface MCToast : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


















SWIFT_CLASS("_TtC15DCloudUTSExtAPI13MCToastConfig")
@interface MCToastConfig : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end





SWIFT_CLASS_NAMED("Node")
@interface UTSSDKModulesDCloudUniRichTextNode : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable attrs;
@property (nonatomic, copy) NSArray<UTSSDKModulesDCloudUniRichTextNode *> * _Nullable children;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, copy) NSString * _Nullable node;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("OnHostThemeChangeCallbackResult")
@interface UTSSDKModulesDCloudUniThemeOnHostThemeChangeCallbackResult : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified hostTheme;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("OnThemeChangeCallbackResult")
@interface UTSSDKModulesDCloudUniThemeOnThemeChangeCallbackResult : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified theme;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("OpenAppAuthorizeSettingComplete")
@interface UTSSDKModulesDCloudUniOpenAppAuthorizeSettingOpenAppAuthorizeSettingComplete : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified errMsg;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("OpenAppAuthorizeSettingFail")
@interface UTSSDKModulesDCloudUniOpenAppAuthorizeSettingOpenAppAuthorizeSettingFail : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified errMsg;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSSDKModulesDCloudUniOpenAppAuthorizeSettingOpenAppAuthorizeSettingSuccess;

SWIFT_CLASS_NAMED("OpenAppAuthorizeSettingOptions")
@interface UTSSDKModulesDCloudUniOpenAppAuthorizeSettingOpenAppAuthorizeSettingOptions : NSObject
@property (nonatomic, copy) void (^ _Nullable success)(UTSSDKModulesDCloudUniOpenAppAuthorizeSettingOpenAppAuthorizeSettingSuccess * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable fail)(UTSSDKModulesDCloudUniOpenAppAuthorizeSettingOpenAppAuthorizeSettingFail * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable complete)(UTSSDKModulesDCloudUniOpenAppAuthorizeSettingOpenAppAuthorizeSettingComplete * _Nonnull);
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("OpenAppAuthorizeSettingOptionsJSONObject")
@interface UTSSDKModulesDCloudUniOpenAppAuthorizeSettingOpenAppAuthorizeSettingOptionsJSONObject : NSObject
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("OpenAppAuthorizeSettingSuccess")
@interface UTSSDKModulesDCloudUniOpenAppAuthorizeSettingOpenAppAuthorizeSettingSuccess : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified errMsg;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("OsThemeChangeResult")
@interface UTSSDKModulesDCloudUniThemeOsThemeChangeResult : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified osTheme;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("Popover")
@interface UTSSDKModulesDCloudUniActionSheetPopover : NSObject
@property (nonatomic, strong) NSNumber * _Null_unspecified top;
@property (nonatomic, strong) NSNumber * _Null_unspecified left;
@property (nonatomic, strong) NSNumber * _Null_unspecified width;
@property (nonatomic, strong) NSNumber * _Null_unspecified height;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("PrivacyChangeResult")
@interface UTSSDKModulesDCloudUniPrivacyPrivacyChangeResult : NSObject
@property (nonatomic) BOOL needAuthorization;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSSDKModulesDCloudUniStorageRemoveStorageSuccess;

SWIFT_CLASS_NAMED("RemoveStorageOptions")
@interface UTSSDKModulesDCloudUniStorageRemoveStorageOptions : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified key;
@property (nonatomic, copy) void (^ _Nullable success)(UTSSDKModulesDCloudUniStorageRemoveStorageSuccess * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable fail)(UniError * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable complete)(id _Nonnull);
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("RemoveStorageOptionsJSONObject")
@interface UTSSDKModulesDCloudUniStorageRemoveStorageOptionsJSONObject : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified key;
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("RemoveStorageSuccess")
@interface UTSSDKModulesDCloudUniStorageRemoveStorageSuccess : NSObject
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("SafeArea")
@interface UTSSDKModulesDCloudUniGetSystemInfoSafeArea : NSObject
@property (nonatomic, strong) NSNumber * _Null_unspecified left;
@property (nonatomic, strong) NSNumber * _Null_unspecified right;
@property (nonatomic, strong) NSNumber * _Null_unspecified top;
@property (nonatomic, strong) NSNumber * _Null_unspecified bottom;
@property (nonatomic, strong) NSNumber * _Null_unspecified width;
@property (nonatomic, strong) NSNumber * _Null_unspecified height;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("SafeAreaInsets")
@interface UTSSDKModulesDCloudUniGetSystemInfoSafeAreaInsets : NSObject
@property (nonatomic, strong) NSNumber * _Null_unspecified left;
@property (nonatomic, strong) NSNumber * _Null_unspecified right;
@property (nonatomic, strong) NSNumber * _Null_unspecified top;
@property (nonatomic, strong) NSNumber * _Null_unspecified bottom;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSSDKModulesDCloudUniThemeSetAppThemeSuccessResult;

SWIFT_CLASS_NAMED("SetAppThemeOptions")
@interface UTSSDKModulesDCloudUniThemeSetAppThemeOptions : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified theme;
@property (nonatomic, copy) void (^ _Nullable success)(UTSSDKModulesDCloudUniThemeSetAppThemeSuccessResult * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable complete)(id _Nonnull);
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("SetAppThemeOptionsJSONObject")
@interface UTSSDKModulesDCloudUniThemeSetAppThemeOptionsJSONObject : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified theme;
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("SetAppThemeSuccessResult")
@interface UTSSDKModulesDCloudUniThemeSetAppThemeSuccessResult : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified theme;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSSDKModulesDCloudUniStorageSetStorageSuccess;

SWIFT_CLASS_NAMED("SetStorageOptions")
@interface UTSSDKModulesDCloudUniStorageSetStorageOptions : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified key;
@property (nonatomic) id _Null_unspecified data;
@property (nonatomic, copy) void (^ _Nullable success)(UTSSDKModulesDCloudUniStorageSetStorageSuccess * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable fail)(UniError * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable complete)(id _Nonnull);
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("SetStorageOptionsJSONObject")
@interface UTSSDKModulesDCloudUniStorageSetStorageOptionsJSONObject : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified key;
@property (nonatomic) id _Null_unspecified data;
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("SetStorageSuccess")
@interface UTSSDKModulesDCloudUniStorageSetStorageSuccess : NSObject
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ShowActionSheetOptions")
@interface UTSSDKModulesDCloudUniActionSheetShowActionSheetOptions : NSObject
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable alertText;
@property (nonatomic, copy) NSArray<NSString *> * _Null_unspecified itemList;
@property (nonatomic, copy) NSString * _Nullable itemColor;
@property (nonatomic, strong) UTSSDKModulesDCloudUniActionSheetPopover * _Nullable popover;
@property (nonatomic, copy) NSString * _Nullable titleColor;
@property (nonatomic, copy) NSString * _Nullable cancelText;
@property (nonatomic, copy) NSString * _Nullable cancelColor;
@property (nonatomic, copy) NSString * _Nullable backgroundColor;
@property (nonatomic, copy) void (^ _Nullable complete)(id _Nonnull);
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ShowActionSheetOptionsJSONObject")
@interface UTSSDKModulesDCloudUniActionSheetShowActionSheetOptionsJSONObject : NSObject
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable alertText;
@property (nonatomic, copy) NSArray<NSString *> * _Null_unspecified itemList;
@property (nonatomic, copy) NSString * _Nullable itemColor;
@property (nonatomic, strong) UTSSDKModulesDCloudUniActionSheetPopover * _Nullable popover;
@property (nonatomic, copy) NSString * _Nullable titleColor;
@property (nonatomic, copy) NSString * _Nullable cancelText;
@property (nonatomic, copy) NSString * _Nullable cancelColor;
@property (nonatomic, copy) NSString * _Nullable backgroundColor;
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ShowActionSheetSuccessImpl")
@interface UTSSDKModulesDCloudUniActionSheetShowActionSheetSuccessImpl : NSObject
@property (nonatomic, strong) NSNumber * _Nonnull tapIndex;
@property (nonatomic, copy) NSString * _Nonnull errMsg;
- (nonnull instancetype)init:(NSNumber * _Nonnull)tapIndex :(NSString * _Nonnull)errMsg OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UTSSDKModulesDCloudUniPromptShowLoadingSuccess;

SWIFT_CLASS_NAMED("ShowLoadingOptions")
@interface UTSSDKModulesDCloudUniPromptShowLoadingOptions : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified title;
@property (nonatomic) BOOL mask;
@property (nonatomic, copy) void (^ _Nullable success)(UTSSDKModulesDCloudUniPromptShowLoadingSuccess * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable complete)(id _Nonnull);
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ShowLoadingOptionsJSONObject")
@interface UTSSDKModulesDCloudUniPromptShowLoadingOptionsJSONObject : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified title;
@property (nonatomic) BOOL mask;
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ShowLoadingSuccess")
@interface UTSSDKModulesDCloudUniPromptShowLoadingSuccess : NSObject
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSSDKModulesDCloudUniModalUniShowModalResult;

SWIFT_CLASS_NAMED("ShowModalOptions")
@interface UTSSDKModulesDCloudUniModalShowModalOptions : NSObject
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic) BOOL showCancel;
@property (nonatomic, copy) NSString * _Nullable cancelText;
@property (nonatomic, copy) NSString * _Nullable cancelColor;
@property (nonatomic, copy) NSString * _Nullable confirmText;
@property (nonatomic, copy) NSString * _Nullable confirmColor;
@property (nonatomic) BOOL editable;
@property (nonatomic, copy) NSString * _Nullable placeholderText;
@property (nonatomic, copy) void (^ _Nullable success)(UTSSDKModulesDCloudUniModalUniShowModalResult * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable complete)(id _Nonnull);
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ShowModalOptionsJSONObject")
@interface UTSSDKModulesDCloudUniModalShowModalOptionsJSONObject : NSObject
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic) BOOL showCancel;
@property (nonatomic, copy) NSString * _Nullable cancelText;
@property (nonatomic, copy) NSString * _Nullable cancelColor;
@property (nonatomic, copy) NSString * _Nullable confirmText;
@property (nonatomic, copy) NSString * _Nullable confirmColor;
@property (nonatomic) BOOL editable;
@property (nonatomic, copy) NSString * _Nullable placeholderText;
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSSDKModulesDCloudUniPromptShowToastSuccess;

SWIFT_CLASS_NAMED("ShowToastOptions")
@interface UTSSDKModulesDCloudUniPromptShowToastOptions : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified title;
@property (nonatomic, copy) NSString * _Nullable icon;
@property (nonatomic, copy) NSString * _Nullable image;
@property (nonatomic) BOOL mask;
@property (nonatomic, strong) NSNumber * _Nullable duration;
@property (nonatomic, copy) NSString * _Nullable position;
@property (nonatomic, copy) void (^ _Nullable success)(UTSSDKModulesDCloudUniPromptShowToastSuccess * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable complete)(id _Nonnull);
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ShowToastOptionsJSONObject")
@interface UTSSDKModulesDCloudUniPromptShowToastOptionsJSONObject : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified title;
@property (nonatomic, copy) NSString * _Nullable icon;
@property (nonatomic, copy) NSString * _Nullable image;
@property (nonatomic) BOOL mask;
@property (nonatomic, strong) NSNumber * _Nullable duration;
@property (nonatomic, copy) NSString * _Nullable position;
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ShowToastSuccess")
@interface UTSSDKModulesDCloudUniPromptShowToastSuccess : NSObject
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("StorageTool")
@interface UTSSDKModulesDCloudUniStorageStorageTool : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end













SWIFT_CLASS_NAMED("UTSSDKModulesDCloudUniActionSheetIndexSwift")
@interface UTSSDKModulesDCloudUniActionSheetIndexSwift : NSObject
+ (void)s_showActionSheetByJs:(UTSSDKModulesDCloudUniActionSheetShowActionSheetOptionsJSONObject * _Nonnull)options;
+ (void)s_hideActionSheetByJs;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ArrayBuffer;

SWIFT_CLASS_NAMED("UTSSDKModulesDCloudUniArrayBufferToBase64IndexSwift")
@interface UTSSDKModulesDCloudUniArrayBufferToBase64IndexSwift : NSObject
+ (NSString * _Nonnull)s_arrayBufferToBase64ByJs:(ArrayBuffer * _Nonnull)arrayBuffer SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UTSSDKModulesDCloudUniBase64ToArrayBufferIndexSwift")
@interface UTSSDKModulesDCloudUniBase64ToArrayBufferIndexSwift : NSObject
+ (ArrayBuffer * _Nonnull)s_base64ToArrayBufferByJs:(NSString * _Nonnull)base64 SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UTSSDKModulesDCloudUniCrashIndexSwift")
@interface UTSSDKModulesDCloudUniCrashIndexSwift : NSObject
+ (void)s___onAppCrashByJs:(UTSCallback * _Nonnull)callback;
+ (void)s___offAppCrashByJs;
+ (NSArray<NSDictionary<NSString *, id> *> * _Nonnull)s___getAppCrashInfoByJs SWIFT_WARN_UNUSED_RESULT;
+ (void)s___deleteAppCrashInfoByJs:(NSString * _Nullable)id;
+ (void)s___createAppCrashByJs;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UTSSDKModulesDCloudUniExitIndexSwift")
@interface UTSSDKModulesDCloudUniExitIndexSwift : NSObject
+ (void)s_exitByJs:(UTSSDKModulesDCloudUniExitExitOptionsJSONObject * _Nullable)options;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UTSSDKModulesDCloudUniGetAppAuthorizeSettingIndexSwift")
@interface UTSSDKModulesDCloudUniGetAppAuthorizeSettingIndexSwift : NSObject
+ (UTSSDKModulesDCloudUniGetAppAuthorizeSettingGetAppAuthorizeSettingResult * _Nonnull)s_getAppAuthorizeSettingByJs SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UTSSDKModulesDCloudUniGetAppBaseInfoIndexSwift")
@interface UTSSDKModulesDCloudUniGetAppBaseInfoIndexSwift : NSObject
+ (UTSSDKModulesDCloudUniGetAppBaseInfoGetAppBaseInfoResult * _Nonnull)s_getAppBaseInfoByJs:(UTSSDKModulesDCloudUniGetAppBaseInfoGetAppBaseInfoOptionsJSONObject * _Nullable)options SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UTSSDKModulesDCloudUniGetDeviceInfoIndexSwift")
@interface UTSSDKModulesDCloudUniGetDeviceInfoIndexSwift : NSObject
+ (BOOL)s_isSimulatorByJs SWIFT_WARN_UNUSED_RESULT;
+ (UTSSDKModulesDCloudUniGetDeviceInfoGetDeviceInfoResult * _Nonnull)s_getDeviceInfoByJs:(UTSSDKModulesDCloudUniGetDeviceInfoGetDeviceInfoOptionsJSONObject * _Nullable)options SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol UniElement;

SWIFT_CLASS_NAMED("UTSSDKModulesDCloudUniGetElementByIdIndexSwift")
@interface UTSSDKModulesDCloudUniGetElementByIdIndexSwift : NSObject
+ (id <UniElement> _Nullable)s_getElementByIdByJs:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UTSSDKModulesDCloudUniGetSystemInfoIndexSwift")
@interface UTSSDKModulesDCloudUniGetSystemInfoIndexSwift : NSObject
+ (void)s_getSystemInfoByJs:(UTSSDKModulesDCloudUniGetSystemInfoGetSystemInfoOptionsJSONObject * _Nonnull)options;
+ (UTSSDKModulesDCloudUniGetSystemInfoGetSystemInfoResult * _Nonnull)s_getSystemInfoSyncByJs SWIFT_WARN_UNUSED_RESULT;
+ (UTSSDKModulesDCloudUniGetSystemInfoGetWindowInfoResult * _Nonnull)s_getWindowInfoByJs SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UTSSDKModulesDCloudUniGetSystemSettingIndexSwift")
@interface UTSSDKModulesDCloudUniGetSystemSettingIndexSwift : NSObject
+ (UTSSDKModulesDCloudUniGetSystemSettingGetSystemSettingResult * _Nonnull)s_getSystemSettingByJs SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UTSSDKModulesDCloudUniModalIndexSwift")
@interface UTSSDKModulesDCloudUniModalIndexSwift : NSObject
+ (id <UniPage> _Nullable)s_showModalByJs:(UTSSDKModulesDCloudUniModalShowModalOptionsJSONObject * _Nonnull)options SWIFT_WARN_UNUSED_RESULT;
+ (void)s_hideModalByJs:(UTSSDKModulesDCloudUniModalHideModalOptionsJSONObject * _Nullable)options;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UTSSDKModulesDCloudUniOpenAppAuthorizeSettingIndexSwift")
@interface UTSSDKModulesDCloudUniOpenAppAuthorizeSettingIndexSwift : NSObject
+ (void)s_openAppAuthorizeSettingByJs:(UTSSDKModulesDCloudUniOpenAppAuthorizeSettingOpenAppAuthorizeSettingOptionsJSONObject * _Nonnull)options;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UTSSDKModulesDCloudUniPrivacyIndexSwift")
@interface UTSSDKModulesDCloudUniPrivacyIndexSwift : NSObject
+ (void)s_getPrivacySettingByJs:(UTSSDKModulesDCloudUniPrivacyGetPrivacySettingOptionsJSONObject * _Nonnull)options;
+ (void)s_resetPrivacyAuthorizationByJs;
+ (NSNumber * _Nonnull)s_onPrivacyAuthorizationChangeByJs:(UTSCallback * _Nonnull)callback SWIFT_WARN_UNUSED_RESULT;
+ (void)s_offPrivacyAuthorizationChangeByJs:(NSNumber * _Nonnull)id;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UTSSDKModulesDCloudUniPromptIndexSwift")
@interface UTSSDKModulesDCloudUniPromptIndexSwift : NSObject
+ (void)s_showToastByJs:(UTSSDKModulesDCloudUniPromptShowToastOptionsJSONObject * _Nonnull)options;
+ (void)s_hideToastByJs;
+ (void)s_showLoadingByJs:(UTSSDKModulesDCloudUniPromptShowLoadingOptionsJSONObject * _Nonnull)options;
+ (void)s_hideLoadingByJs;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UTSSDKModulesDCloudUniRpx2pxIndexSwift")
@interface UTSSDKModulesDCloudUniRpx2pxIndexSwift : NSObject
+ (NSNumber * _Nonnull)s_rpx2pxByJs:(NSNumber * _Nonnull)number SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UTSSDKModulesDCloudUniStorageIndexSwift")
@interface UTSSDKModulesDCloudUniStorageIndexSwift : NSObject
+ (void)s_setStorageByJs:(UTSSDKModulesDCloudUniStorageSetStorageOptionsJSONObject * _Nonnull)options;
+ (void)s_setStorageSyncByJs:(NSString * _Nonnull)key :(id _Nonnull)data;
+ (void)s_getStorageByJs:(UTSSDKModulesDCloudUniStorageGetStorageOptionsJSONObject * _Nonnull)options;
+ (id _Nullable)s_getStorageSyncByJs:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
+ (void)s_getStorageInfoByJs:(UTSSDKModulesDCloudUniStorageGetStorageInfoOptionsJSONObject * _Nonnull)options;
+ (UTSSDKModulesDCloudUniStorageGetStorageInfoSuccess * _Nonnull)s_getStorageInfoSyncByJs SWIFT_WARN_UNUSED_RESULT;
+ (void)s_removeStorageByJs:(UTSSDKModulesDCloudUniStorageRemoveStorageOptionsJSONObject * _Nonnull)options;
+ (void)s_removeStorageSyncByJs:(NSString * _Nonnull)key;
+ (void)s_clearStorageByJs:(UTSSDKModulesDCloudUniStorageClearStorageOptionsJSONObject * _Nullable)option;
+ (void)s_clearStorageSyncByJs;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UTSSDKModulesDCloudUniThemeIndexSwift")
@interface UTSSDKModulesDCloudUniThemeIndexSwift : NSObject
+ (NSNumber * _Nonnull)s_onOsThemeChangeByJs:(UTSCallback * _Nonnull)callback SWIFT_WARN_UNUSED_RESULT;
+ (void)s_offOsThemeChangeByJs:(NSNumber * _Nonnull)id;
+ (void)s_setAppThemeByJs:(UTSSDKModulesDCloudUniThemeSetAppThemeOptionsJSONObject * _Nonnull)options;
+ (NSNumber * _Nonnull)s_onAppThemeChangeByJs:(UTSCallback * _Nonnull)callback SWIFT_WARN_UNUSED_RESULT;
+ (void)s_offAppThemeChangeByJs:(NSNumber * _Nonnull)id;
+ (NSNumber * _Nonnull)s_onHostThemeChangeByJs:(UTSCallback * _Nonnull)callback SWIFT_WARN_UNUSED_RESULT;
+ (void)s_offHostThemeChangeByJs:(NSNumber * _Nonnull)id;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UniHideModalResult")
@interface UTSSDKModulesDCloudUniModalUniHideModalResult : NSObject
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UniRichTextElementRegister")
@interface UniRichTextElementRegister : NSObject
+ (void)registerComponent;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UniRichTextItemClickEventDetail")
@interface UTSSDKModulesDCloudUniRichTextUniRichTextItemClickEventDetail : NSObject
@property (nonatomic, copy) NSString * _Nullable src;
@property (nonatomic, copy) NSString * _Nullable href;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UniShowModalResult")
@interface UTSSDKModulesDCloudUniModalUniShowModalResult : NSObject
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic) BOOL cancel;
@property (nonatomic) BOOL confirm;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
